set_property SRC_FILE_INFO {cfile:C:/xup/fpga_flow/2014_2_artix7_labs/lab5/lab5.srcs/constrs_1/new/uart_led.xdc rfile:../../../lab5.srcs/constrs_1/new/uart_led.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property IOB TRUE [get_ports {led_pins[*]}]
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X0Y0 [get_cells {led_ctl_i0/led_o_reg[1]}]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X0Y1 [get_cells {led_ctl_i0/led_o_reg[0]}]
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X0Y18 [get_cells {led_ctl_i0/led_o_reg[3]}]
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X0Y19 [get_cells {led_ctl_i0/led_o_reg[4]}]
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X0Y20 [get_cells {led_ctl_i0/led_o_reg[5]}]
set_property src_info {type:XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X0Y3 [get_cells {led_ctl_i0/led_o_reg[7]}]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X0Y4 [get_cells {led_ctl_i0/led_o_reg[2]}]
set_property src_info {type:XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X0Y43 [get_cells {led_ctl_i0/led_o_reg[6]}]
