# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/lab4/wave_gen_timing.xdc

# XDC: imports/lab4/wave_gen_pins_basys3.xdc

# IP: ip/char_fifo/char_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==char_fifo || ORIG_REF_NAME==char_fifo}]

# XDC: ip/char_fifo/char_fifo/char_fifo_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==char_fifo || ORIG_REF_NAME==char_fifo}] {/U0 }]/U0 ]]

# XDC: ip/char_fifo/char_fifo/char_fifo.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==char_fifo || ORIG_REF_NAME==char_fifo}] {/U0 }]/U0 ]]

# XDC: ip/char_fifo/char_fifo_ooc.xdc
