# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
  set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Labtools 27-147} -limit 4294967295
create_project -in_memory -part xc7a35tcpg236-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]

read_ip c:/xup/fpga_flow/labs/lab6/lab6.srcs/sources_1/ip/ila_led/ila_led.xci
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property is_locked true [get_files c:/xup/fpga_flow/labs/lab6/lab6.srcs/sources_1/ip/ila_led/ila_led.xci]

set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/xup/fpga_flow/labs/lab6/lab6.cache/wt [current_project]
set_property parent.project_dir C:/xup/fpga_flow/labs/lab6 [current_project]
catch { write_hwdef -file ila_led.hwdef }
synth_design -top ila_led -part xc7a35tcpg236-1 -mode out_of_context

rename_ref -prefix_all ila_led_
write_checkpoint -noxdef ila_led.dcp
report_utilization -file ila_led_utilization_synth.rpt -pb ila_led_utilization_synth.pb
if { [catch {
  file copy -force C:/xup/fpga_flow/labs/lab6/lab6.runs/ila_led_synth_1/ila_led.dcp c:/xup/fpga_flow/labs/lab6/lab6.srcs/sources_1/ip/ila_led/ila_led.dcp
  write_verilog -force -mode synth_stub c:/xup/fpga_flow/labs/lab6/lab6.srcs/sources_1/ip/ila_led/ila_led_stub.v
  write_vhdl -force -mode synth_stub c:/xup/fpga_flow/labs/lab6/lab6.srcs/sources_1/ip/ila_led/ila_led_stub.vhdl
  write_verilog -force -mode funcsim c:/xup/fpga_flow/labs/lab6/lab6.srcs/sources_1/ip/ila_led/ila_led_funcsim.v
  write_vhdl -force -mode funcsim c:/xup/fpga_flow/labs/lab6/lab6.srcs/sources_1/ip/ila_led/ila_led_funcsim.vhdl
} _RESULT ] } { 
  send_msg_id runtcl-3 error "Unable to successfully create or copy supporting IP files."
  return -code error
}
