#set_property direction IN [get_ports {clk_pin}]
#set_property direction IN [get_ports {btn_pin}]
#set_property direction IN [get_ports {rxd_pin}]
#set_property direction IN [get_ports {rst_pin}]
#set_property direction OUT [get_ports {led_pins[0]}]
#set_property direction OUT [get_ports {led_pins[1]}]
#set_property direction OUT [get_ports {led_pins[2]}]
#set_property direction OUT [get_ports {led_pins[3]}]
#set_property direction OUT [get_ports {led_pins[4]}]
#set_property direction OUT [get_ports {led_pins[5]}]
#set_property direction OUT [get_ports {led_pins[6]}]
#set_property direction OUT [get_ports {led_pins[7]}]
set_property PACKAGE_PIN W5 [get_ports clk_pin]
set_property IOSTANDARD LVCMOS33 [get_ports clk_pin]
set_property PACKAGE_PIN T18 [get_ports btn_pin]
set_property IOSTANDARD LVCMOS33 [get_ports btn_pin]
set_property PACKAGE_PIN B18 [get_ports rxd_pin]
set_property IOSTANDARD LVCMOS33 [get_ports rxd_pin]
set_property PACKAGE_PIN U18 [get_ports rst_pin]
set_property IOSTANDARD LVCMOS33 [get_ports rst_pin]
set_property IOSTANDARD LVCMOS33 [get_ports {led_pins[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_pins[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_pins[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_pins[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_pins[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_pins[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_pins[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_pins[7]}]
set_property DRIVE 12 [get_ports {led_pins[0]}]
set_property DRIVE 12 [get_ports {led_pins[1]}]
set_property DRIVE 12 [get_ports {led_pins[2]}]
set_property DRIVE 12 [get_ports {led_pins[3]}]
set_property DRIVE 12 [get_ports {led_pins[4]}]
set_property DRIVE 12 [get_ports {led_pins[5]}]
set_property DRIVE 12 [get_ports {led_pins[6]}]
set_property DRIVE 12 [get_ports {led_pins[7]}]
set_property SLEW SLOW [get_ports {led_pins[0]}]
set_property SLEW SLOW [get_ports {led_pins[1]}]
set_property SLEW SLOW [get_ports {led_pins[2]}]
set_property SLEW SLOW [get_ports {led_pins[3]}]
set_property SLEW SLOW [get_ports {led_pins[4]}]
set_property SLEW SLOW [get_ports {led_pins[5]}]
set_property SLEW SLOW [get_ports {led_pins[6]}]
set_property SLEW SLOW [get_ports {led_pins[7]}]

create_clock -period 10.000 -name clk_pin -waveform {0.000 5.000} [get_ports clk_pin]
set_input_delay -clock [get_clocks clk_pin] 0.000 [get_ports {btn_pin rst_pin rxd_pin}]
set_input_delay -clock [get_clocks clk_pin] -min -0.500 [get_ports {btn_pin rst_pin rxd_pin}]
set_output_delay -clock [get_clocks clk_pin] 0.000 [get_ports {led_pins[0] led_pins[1] led_pins[2] led_pins[3] led_pins[4] led_pins[5] led_pins[6] led_pins[7]}]


set_property IOB TRUE [get_ports {led_pins[*]}]
set_property LOC OLOGIC_X0Y0 [get_cells {led_ctl_i0/led_o_reg[1]}]
set_property LOC OLOGIC_X0Y1 [get_cells {led_ctl_i0/led_o_reg[0]}]
set_property LOC OLOGIC_X0Y18 [get_cells {led_ctl_i0/led_o_reg[3]}]
set_property LOC OLOGIC_X0Y19 [get_cells {led_ctl_i0/led_o_reg[4]}]
set_property LOC OLOGIC_X0Y20 [get_cells {led_ctl_i0/led_o_reg[5]}]
set_property LOC OLOGIC_X0Y3 [get_cells {led_ctl_i0/led_o_reg[7]}]
set_property LOC OLOGIC_X0Y4 [get_cells {led_ctl_i0/led_o_reg[2]}]
set_property LOC OLOGIC_X0Y43 [get_cells {led_ctl_i0/led_o_reg[6]}]
set_property PACKAGE_PIN V14 [get_ports {led_pins[0]}]
set_property PACKAGE_PIN U14 [get_ports {led_pins[1]}]
set_property PACKAGE_PIN U15 [get_ports {led_pins[2]}]
set_property PACKAGE_PIN W18 [get_ports {led_pins[3]}]
set_property PACKAGE_PIN V19 [get_ports {led_pins[4]}]
set_property PACKAGE_PIN U19 [get_ports {led_pins[5]}]
set_property PACKAGE_PIN E19 [get_ports {led_pins[6]}]
set_property PACKAGE_PIN U16 [get_ports {led_pins[7]}]
