# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/sy9/sy9.bd
# Block Designs: The module: 'sy9' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: bd/sy9/ip/sy9_D_FlipFlop_Set_Reset_0_0/sy9_D_FlipFlop_Set_Reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sy9_D_FlipFlop_Set_Reset_0_0 || ORIG_REF_NAME==sy9_D_FlipFlop_Set_Reset_0_0}]

# IP: bd/sy9/ip/sy9_xup_nand2_0_0/sy9_xup_nand2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sy9_xup_nand2_0_0 || ORIG_REF_NAME==sy9_xup_nand2_0_0}]

# IP: bd/sy9/ip/sy9_xup_nand2_0_3/sy9_xup_nand2_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sy9_xup_nand2_0_3 || ORIG_REF_NAME==sy9_xup_nand2_0_3}]

# IP: bd/sy9/ip/sy9_xup_nand2_0_4/sy9_xup_nand2_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sy9_xup_nand2_0_4 || ORIG_REF_NAME==sy9_xup_nand2_0_4}]

# IP: bd/sy9/ip/sy9_xup_inv_0_1/sy9_xup_inv_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sy9_xup_inv_0_1 || ORIG_REF_NAME==sy9_xup_inv_0_1}]

# IP: bd/sy9/ip/sy9_xup_nand2_1_0/sy9_xup_nand2_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sy9_xup_nand2_1_0 || ORIG_REF_NAME==sy9_xup_nand2_1_0}]

# IP: bd/sy9/ip/sy9_xup_nand2_1_1/sy9_xup_nand2_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sy9_xup_nand2_1_1 || ORIG_REF_NAME==sy9_xup_nand2_1_1}]

# IP: bd/sy9/ip/sy9_xup_nand2_1_2/sy9_xup_nand2_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sy9_xup_nand2_1_2 || ORIG_REF_NAME==sy9_xup_nand2_1_2}]

# IP: bd/sy9/ip/sy9_xup_inv_0_2/sy9_xup_inv_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sy9_xup_inv_0_2 || ORIG_REF_NAME==sy9_xup_inv_0_2}]

# IP: bd/sy9/ip/sy9_xup_xor2_0_0/sy9_xup_xor2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sy9_xup_xor2_0_0 || ORIG_REF_NAME==sy9_xup_xor2_0_0}]

# IP: bd/sy9/ip/sy9_xup_nand3_0_4/sy9_xup_nand3_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sy9_xup_nand3_0_4 || ORIG_REF_NAME==sy9_xup_nand3_0_4}]

# IP: bd/sy9/ip/sy9_D_FlipFlop_Set_Reset_0_2/sy9_D_FlipFlop_Set_Reset_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sy9_D_FlipFlop_Set_Reset_0_2 || ORIG_REF_NAME==sy9_D_FlipFlop_Set_Reset_0_2}]

# IP: bd/sy9/ip/sy9_xup_nand2_1_3/sy9_xup_nand2_1_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sy9_xup_nand2_1_3 || ORIG_REF_NAME==sy9_xup_nand2_1_3}]

# IP: bd/sy9/ip/sy9_xup_nand2_1_4/sy9_xup_nand2_1_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sy9_xup_nand2_1_4 || ORIG_REF_NAME==sy9_xup_nand2_1_4}]

# IP: bd/sy9/ip/sy9_xup_nand2_1_5/sy9_xup_nand2_1_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sy9_xup_nand2_1_5 || ORIG_REF_NAME==sy9_xup_nand2_1_5}]

# IP: bd/sy9/ip/sy9_xup_inv_1_0/sy9_xup_inv_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sy9_xup_inv_1_0 || ORIG_REF_NAME==sy9_xup_inv_1_0}]

# IP: bd/sy9/ip/sy9_xup_nand3_0_5/sy9_xup_nand3_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sy9_xup_nand3_0_5 || ORIG_REF_NAME==sy9_xup_nand3_0_5}]

# IP: bd/sy9/ip/sy9_xup_nand3_0_6/sy9_xup_nand3_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sy9_xup_nand3_0_6 || ORIG_REF_NAME==sy9_xup_nand3_0_6}]

# IP: bd/sy9/ip/sy9_xup_nand3_0_7/sy9_xup_nand3_0_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sy9_xup_nand3_0_7 || ORIG_REF_NAME==sy9_xup_nand3_0_7}]

# IP: bd/sy9/ip/sy9_xup_inv_2_0/sy9_xup_inv_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sy9_xup_inv_2_0 || ORIG_REF_NAME==sy9_xup_inv_2_0}]

# IP: bd/sy9/ip/sy9_xup_nand3_0_8/sy9_xup_nand3_0_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sy9_xup_nand3_0_8 || ORIG_REF_NAME==sy9_xup_nand3_0_8}]

# IP: bd/sy9/ip/sy9_xup_nand2_8_0/sy9_xup_nand2_8_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sy9_xup_nand2_8_0 || ORIG_REF_NAME==sy9_xup_nand2_8_0}]

# IP: bd/sy9/ip/sy9_xup_nand2_7_0/sy9_xup_nand2_7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sy9_xup_nand2_7_0 || ORIG_REF_NAME==sy9_xup_nand2_7_0}]

# IP: bd/sy9/ip/sy9_xup_nand2_7_1/sy9_xup_nand2_7_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sy9_xup_nand2_7_1 || ORIG_REF_NAME==sy9_xup_nand2_7_1}]

# IP: bd/sy9/ip/sy9_xup_nand2_7_2/sy9_xup_nand2_7_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sy9_xup_nand2_7_2 || ORIG_REF_NAME==sy9_xup_nand2_7_2}]

# IP: bd/sy9/ip/sy9_xup_inv_2_1/sy9_xup_inv_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sy9_xup_inv_2_1 || ORIG_REF_NAME==sy9_xup_inv_2_1}]

# IP: bd/sy9/ip/sy9_xup_nand4_0_10/sy9_xup_nand4_0_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sy9_xup_nand4_0_10 || ORIG_REF_NAME==sy9_xup_nand4_0_10}]

# IP: bd/sy9/ip/sy9_xup_nand4_0_11/sy9_xup_nand4_0_11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sy9_xup_nand4_0_11 || ORIG_REF_NAME==sy9_xup_nand4_0_11}]

# IP: bd/sy9/ip/sy9_xup_nand2_10_0/sy9_xup_nand2_10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sy9_xup_nand2_10_0 || ORIG_REF_NAME==sy9_xup_nand2_10_0}]

# IP: bd/sy9/ip/sy9_xup_nand4_1_0/sy9_xup_nand4_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sy9_xup_nand4_1_0 || ORIG_REF_NAME==sy9_xup_nand4_1_0}]

# IP: bd/sy9/ip/sy9_xup_nand3_3_1/sy9_xup_nand3_3_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sy9_xup_nand3_3_1 || ORIG_REF_NAME==sy9_xup_nand3_3_1}]

# IP: bd/sy9/ip/sy9_xup_nand2_13_0/sy9_xup_nand2_13_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sy9_xup_nand2_13_0 || ORIG_REF_NAME==sy9_xup_nand2_13_0}]

# XDC: bd/sy9/sy9_ooc.xdc
