# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Digital_Clock/clock_wrapper.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1}]

# IP: bd/design_1/ip/design_1_decimal_counter_0_0/design_1_decimal_counter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_decimal_counter_0_0 || ORIG_REF_NAME==design_1_decimal_counter_0_0}]

# IP: bd/design_1/ip/design_1_decimal_counter_1_0/design_1_decimal_counter_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_decimal_counter_1_0 || ORIG_REF_NAME==design_1_decimal_counter_1_0}]

# IP: bd/design_1/ip/design_1_decimal_counter_2_0/design_1_decimal_counter_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_decimal_counter_2_0 || ORIG_REF_NAME==design_1_decimal_counter_2_0}]

# IP: bd/design_1/ip/design_1_decimal_counter_3_0/design_1_decimal_counter_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_decimal_counter_3_0 || ORIG_REF_NAME==design_1_decimal_counter_3_0}]

# IP: bd/design_1/ip/design_1_four_2_input_and_gate_0_0/design_1_four_2_input_and_gate_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_four_2_input_and_gate_0_0 || ORIG_REF_NAME==design_1_four_2_input_and_gate_0_0}]

# IP: bd/design_1/ip/design_1_clk_div_0_0/design_1_clk_div_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_div_0_0 || ORIG_REF_NAME==design_1_clk_div_0_0}]

# IP: bd/design_1/ip/design_1_seg7decimal_0_0/design_1_seg7decimal_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_seg7decimal_0_0 || ORIG_REF_NAME==design_1_seg7decimal_0_0}]

# IP: bd/design_1/ip/design_1_xlconcat_0_1/design_1_xlconcat_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconcat_0_1 || ORIG_REF_NAME==design_1_xlconcat_0_1}]

# IP: bd/design_1/ip/design_1_clk_wiz_0_1/design_1_clk_wiz_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_1 || ORIG_REF_NAME==design_1_clk_wiz_0_1}]

# XDC: bd/design_1/ip/design_1_clk_wiz_0_1/design_1_clk_wiz_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_1 || ORIG_REF_NAME==design_1_clk_wiz_0_1}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_clk_wiz_0_1/design_1_clk_wiz_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_1 || ORIG_REF_NAME==design_1_clk_wiz_0_1}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_clk_wiz_0_1/design_1_clk_wiz_0_1_ooc.xdc

# XDC: bd/design_1/design_1_ooc.xdc
