# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/73974/Documents/vivado/ALU/ALU.cache/wt [current_project]
set_property parent.project_path C:/Users/73974/Documents/vivado/ALU/ALU.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  c:/Users/73974/Documents/vivado/数电学习资料（库）/74IP/XUP_74LS00_1.0
  c:/Users/73974/Documents/vivado/数电学习资料（库）/74IP
  c:/Users/73974/Documents/vivado/数电学习资料（库）
} [current_project]
set_property ip_output_repo c:/Users/73974/Documents/vivado/ALU/ALU.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/Users/73974/Documents/vivado/ALU/ALU.srcs/sources_1/bd/ALU/ALU.bd
set_property used_in_implementation false [get_files -all C:/Users/73974/Documents/vivado/ALU/ALU.srcs/sources_1/bd/ALU/ALU_ooc.xdc]
set_property is_locked true [get_files C:/Users/73974/Documents/vivado/ALU/ALU.srcs/sources_1/bd/ALU/ALU.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/73974/Documents/vivado/ALU/ALU.srcs/constrs_1/new/ALU.xdc
set_property used_in_implementation false [get_files C:/Users/73974/Documents/vivado/ALU/ALU.srcs/constrs_1/new/ALU.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top ALU -part xc7a35tcpg236-1


write_checkpoint -force -noxdef ALU.dcp

catch { report_utilization -file ALU_utilization_synth.rpt -pb ALU_utilization_synth.pb }
