# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/ALU.xdc

# Block Designs: bd/ALU/ALU.bd
# Block Designs: The module: 'ALU' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: bd/ALU/ip/ALU_xup_and2_0_0/ALU_xup_and2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ALU_xup_and2_0_0 || ORIG_REF_NAME==ALU_xup_and2_0_0}]

# IP: bd/ALU/ip/ALU_xup_inv_0_0/ALU_xup_inv_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ALU_xup_inv_0_0 || ORIG_REF_NAME==ALU_xup_inv_0_0}]

# IP: bd/ALU/ip/ALU_xup_inv_0_1/ALU_xup_inv_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ALU_xup_inv_0_1 || ORIG_REF_NAME==ALU_xup_inv_0_1}]

# IP: bd/ALU/ip/ALU_xup_or2_0_0/ALU_xup_or2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ALU_xup_or2_0_0 || ORIG_REF_NAME==ALU_xup_or2_0_0}]

# IP: bd/ALU/ip/ALU_xup_xor2_0_0/ALU_xup_xor2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ALU_xup_xor2_0_0 || ORIG_REF_NAME==ALU_xup_xor2_0_0}]

# IP: bd/ALU/ip/ALU_mux_8_to_1_0_0/ALU_mux_8_to_1_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ALU_mux_8_to_1_0_0 || ORIG_REF_NAME==ALU_mux_8_to_1_0_0}]

# IP: bd/ALU/ip/ALU_decode138_0_0/ALU_decode138_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ALU_decode138_0_0 || ORIG_REF_NAME==ALU_decode138_0_0}]

# IP: bd/ALU/ip/ALU_xup_nand4_0_0/ALU_xup_nand4_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ALU_xup_nand4_0_0 || ORIG_REF_NAME==ALU_xup_nand4_0_0}]

# IP: bd/ALU/ip/ALU_xup_nand4_0_1/ALU_xup_nand4_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ALU_xup_nand4_0_1 || ORIG_REF_NAME==ALU_xup_nand4_0_1}]

# IP: bd/ALU/ip/ALU_xup_nand4_0_2/ALU_xup_nand4_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ALU_xup_nand4_0_2 || ORIG_REF_NAME==ALU_xup_nand4_0_2}]

# IP: bd/ALU/ip/ALU_xup_inv_0_2/ALU_xup_inv_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ALU_xup_inv_0_2 || ORIG_REF_NAME==ALU_xup_inv_0_2}]

# IP: bd/ALU/ip/ALU_xup_inv_0_3/ALU_xup_inv_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ALU_xup_inv_0_3 || ORIG_REF_NAME==ALU_xup_inv_0_3}]

# IP: bd/ALU/ip/ALU_xup_nand4_1_0/ALU_xup_nand4_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ALU_xup_nand4_1_0 || ORIG_REF_NAME==ALU_xup_nand4_1_0}]

# IP: bd/ALU/ip/ALU_xup_nand4_1_1/ALU_xup_nand4_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ALU_xup_nand4_1_1 || ORIG_REF_NAME==ALU_xup_nand4_1_1}]

# IP: bd/ALU/ip/ALU_xup_inv_4_0/ALU_xup_inv_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ALU_xup_inv_4_0 || ORIG_REF_NAME==ALU_xup_inv_4_0}]

# IP: bd/ALU/ip/ALU_xup_nand2_1_0/ALU_xup_nand2_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ALU_xup_nand2_1_0 || ORIG_REF_NAME==ALU_xup_nand2_1_0}]

# IP: bd/ALU/ip/ALU_xup_nand3_0_0/ALU_xup_nand3_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ALU_xup_nand3_0_0 || ORIG_REF_NAME==ALU_xup_nand3_0_0}]

# IP: bd/ALU/ip/ALU_xup_nand4_5_0/ALU_xup_nand4_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ALU_xup_nand4_5_0 || ORIG_REF_NAME==ALU_xup_nand4_5_0}]

# IP: bd/ALU/ip/ALU_xup_nand5_0_0/ALU_xup_nand5_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ALU_xup_nand5_0_0 || ORIG_REF_NAME==ALU_xup_nand5_0_0}]

# XDC: bd/ALU/ALU_ooc.xdc
