set_property PACKAGE_PIN L3 [get_ports {seg[6]}]
set_property PACKAGE_PIN N1 [get_ports {seg[5]}]
set_property PACKAGE_PIN L5 [get_ports {seg[4]}]
set_property PACKAGE_PIN L4 [get_ports {seg[3]}]
set_property PACKAGE_PIN K3 [get_ports {seg[2]}]
set_property PACKAGE_PIN M2 [get_ports {seg[1]}]
set_property PACKAGE_PIN L6 [get_ports {seg[0]}]
set_property PACKAGE_PIN E3 [get_ports clk]
set_property PACKAGE_PIN M6 [get_ports {ans[1]}]
set_property PACKAGE_PIN N6 [get_ports {ans[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {seg[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports {ans[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ans[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {ans[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ans[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ans[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ans[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ans[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ans[2]}]
set_property PACKAGE_PIN M1 [get_ports {ans[7]}]
set_property PACKAGE_PIN L1 [get_ports {ans[6]}]
set_property PACKAGE_PIN N4 [get_ports {ans[5]}]
set_property PACKAGE_PIN N2 [get_ports {ans[4]}]
set_property PACKAGE_PIN N5 [get_ports {ans[3]}]
set_property PACKAGE_PIN M3 [get_ports {ans[2]}]
set_property PACKAGE_PIN U9 [get_ports reset]

