# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
add_files -quiet C:/xup/fpga_flow/labs/lab4_ipi/lab4_ipi.runs/clk_core_synth_1/clk_core.dcp
set_property used_in_implementation false [get_files C:/xup/fpga_flow/labs/lab4_ipi/lab4_ipi.runs/clk_core_synth_1/clk_core.dcp]

add_files C:/xup/fpga_flow/labs/lab4_ipi/lab4_ipi.srcs/sources_1/bd/char_fifo/char_fifo.bd
set_property used_in_implementation false [get_files -all c:/xup/fpga_flow/labs/lab4_ipi/lab4_ipi.srcs/sources_1/bd/char_fifo/ip/char_fifo_fifo_generator_0_1/char_fifo_fifo_generator_0_1/char_fifo_fifo_generator_0_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/xup/fpga_flow/labs/lab4_ipi/lab4_ipi.srcs/sources_1/bd/char_fifo/ip/char_fifo_fifo_generator_0_1/char_fifo_fifo_generator_0_1/char_fifo_fifo_generator_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/xup/fpga_flow/labs/lab4_ipi/lab4_ipi.srcs/sources_1/bd/char_fifo/ip/char_fifo_fifo_generator_0_1/char_fifo_fifo_generator_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/xup/fpga_flow/labs/lab4_ipi/lab4_ipi.srcs/sources_1/bd/char_fifo/char_fifo_ooc.xdc]
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property is_locked true [get_files C:/xup/fpga_flow/labs/lab4_ipi/lab4_ipi.srcs/sources_1/bd/char_fifo/char_fifo.bd]

read_verilog -library xil_defaultlib {
  C:/xup/fpga_flow/labs/lab4_ipi/lab4_ipi.srcs/sources_1/imports/lab4/meta_harden.v
  C:/xup/fpga_flow/labs/lab4_ipi/lab4_ipi.srcs/sources_1/imports/lab4/uart_tx_ctl.v
  C:/xup/fpga_flow/labs/lab4_ipi/lab4_ipi.srcs/sources_1/imports/lab4/uart_rx_ctl.v
  C:/xup/fpga_flow/labs/lab4_ipi/lab4_ipi.srcs/sources_1/imports/lab4/uart_baud_gen.v
  C:/xup/fpga_flow/labs/lab4_ipi/lab4_ipi.srcs/sources_1/imports/lab4/to_bcd.v
  C:/xup/fpga_flow/labs/lab4_ipi/lab4_ipi.srcs/sources_1/imports/lab4/reset_bridge.v
  C:/xup/fpga_flow/labs/lab4_ipi/lab4_ipi.srcs/sources_1/imports/lab4/out_ddr_flop.v
  C:/xup/fpga_flow/labs/lab4_ipi/lab4_ipi.srcs/sources_1/imports/lab4/debouncer.v
  C:/xup/fpga_flow/labs/lab4_ipi/lab4_ipi.srcs/sources_1/imports/lab4/clk_div.v
  C:/xup/fpga_flow/labs/lab4_ipi/lab4_ipi.srcs/sources_1/imports/lab4/uart_tx.v
  C:/xup/fpga_flow/labs/lab4_ipi/lab4_ipi.srcs/sources_1/imports/lab4/uart_rx.v
  C:/xup/fpga_flow/labs/lab4_ipi/lab4_ipi.srcs/sources_1/imports/lab4/samp_ram.v
  C:/xup/fpga_flow/labs/lab4_ipi/lab4_ipi.srcs/sources_1/imports/lab4/samp_gen.v
  C:/xup/fpga_flow/labs/lab4_ipi/lab4_ipi.srcs/sources_1/imports/lab4/rst_gen.v
  C:/xup/fpga_flow/labs/lab4_ipi/lab4_ipi.srcs/sources_1/imports/lab4/resp_gen.v
  C:/xup/fpga_flow/labs/lab4_ipi/lab4_ipi.srcs/sources_1/imports/lab4/lb_ctl.v
  C:/xup/fpga_flow/labs/lab4_ipi/lab4_ipi.srcs/sources_1/imports/lab4/dac_spi.v
  C:/xup/fpga_flow/labs/lab4_ipi/lab4_ipi.srcs/sources_1/imports/lab4/cmd_parse.v
  C:/xup/fpga_flow/labs/lab4_ipi/lab4_ipi.srcs/sources_1/imports/lab4/clk_gen.v
  C:/xup/fpga_flow/labs/lab4_ipi/lab4_ipi.srcs/sources_1/imports/lab4/clkx_bus.v
  C:/xup/fpga_flow/labs/lab4_ipi/lab4_ipi.srcs/sources_1/imports/lab4/wave_gen.v
}
read_xdc C:/xup/fpga_flow/labs/lab4_ipi/lab4_ipi.srcs/constrs_1/imports/lab4/wave_gen_timing.xdc
set_property used_in_implementation false [get_files C:/xup/fpga_flow/labs/lab4_ipi/lab4_ipi.srcs/constrs_1/imports/lab4/wave_gen_timing.xdc]

read_xdc C:/xup/fpga_flow/labs/lab4_ipi/lab4_ipi.srcs/constrs_1/imports/lab4/wave_gen_pins_basys3.xdc
set_property used_in_implementation false [get_files C:/xup/fpga_flow/labs/lab4_ipi/lab4_ipi.srcs/constrs_1/imports/lab4/wave_gen_pins_basys3.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
read_xdc dont_buffer.xdc
set_property used_in_implementation false [get_files dont_buffer.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/xup/fpga_flow/labs/lab4_ipi/lab4_ipi.cache/wt [current_project]
set_property parent.project_dir C:/xup/fpga_flow/labs/lab4_ipi [current_project]
catch { write_hwdef -file wave_gen.hwdef }
synth_design -top wave_gen -part xc7a35tcpg236-1
write_checkpoint wave_gen.dcp
report_utilization -file wave_gen_utilization_synth.rpt -pb wave_gen_utilization_synth.pb
