# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/cpu1.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1}]

# IP: bd/design_1/ip/design_1_PC_0_0/design_1_PC_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_PC_0_0 || ORIG_REF_NAME==design_1_PC_0_0}]

# IP: bd/design_1/ip/design_1_InsMemory_0_0/design_1_InsMemory_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_InsMemory_0_0 || ORIG_REF_NAME==design_1_InsMemory_0_0}]

# IP: bd/design_1/ip/design_1_ControlUnit_0_0/design_1_ControlUnit_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ControlUnit_0_0 || ORIG_REF_NAME==design_1_ControlUnit_0_0}]

# IP: bd/design_1/ip/design_1_RegisterFile_0_1/design_1_RegisterFile_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_RegisterFile_0_1 || ORIG_REF_NAME==design_1_RegisterFile_0_1}]

# IP: bd/design_1/ip/design_1_DataMem_0_0/design_1_DataMem_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_DataMem_0_0 || ORIG_REF_NAME==design_1_DataMem_0_0}]

# IP: bd/design_1/ip/design_1_ALU_0_0/design_1_ALU_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ALU_0_0 || ORIG_REF_NAME==design_1_ALU_0_0}]

# IP: bd/design_1/ip/design_1_SignZeroExtend_0_0/design_1_SignZeroExtend_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_SignZeroExtend_0_0 || ORIG_REF_NAME==design_1_SignZeroExtend_0_0}]

# IP: bd/design_1/ip/design_1_MuxForReadData1_0_0/design_1_MuxForReadData1_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_MuxForReadData1_0_0 || ORIG_REF_NAME==design_1_MuxForReadData1_0_0}]

# IP: bd/design_1/ip/design_1_MuxForReadData2_0_0/design_1_MuxForReadData2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_MuxForReadData2_0_0 || ORIG_REF_NAME==design_1_MuxForReadData2_0_0}]

# IP: bd/design_1/ip/design_1_MuxForWriteData_0_0/design_1_MuxForWriteData_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_MuxForWriteData_0_0 || ORIG_REF_NAME==design_1_MuxForWriteData_0_0}]

# IP: bd/design_1/ip/design_1_MuxForWriteReg_0_1/design_1_MuxForWriteReg_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_MuxForWriteReg_0_1 || ORIG_REF_NAME==design_1_MuxForWriteReg_0_1}]

# IP: bd/design_1/ip/design_1_DisplayControl_0_0/design_1_DisplayControl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_DisplayControl_0_0 || ORIG_REF_NAME==design_1_DisplayControl_0_0}]

# IP: bd/design_1/ip/design_1_x7seg_msg_0_0/design_1_x7seg_msg_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_x7seg_msg_0_0 || ORIG_REF_NAME==design_1_x7seg_msg_0_0}]

# IP: bd/design_1/ip/design_1_CLK_div1_0_0/design_1_CLK_div1_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_CLK_div1_0_0 || ORIG_REF_NAME==design_1_CLK_div1_0_0}]

# IP: bd/design_1/ip/design_1_choose_0_0/design_1_choose_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_choose_0_0 || ORIG_REF_NAME==design_1_choose_0_0}]

# IP: bd/design_1/ip/design_1_clk_40hz_0_0/design_1_clk_40hz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_40hz_0_0 || ORIG_REF_NAME==design_1_clk_40hz_0_0}]

# IP: bd/design_1/ip/design_1_avoidshake_0_0/design_1_avoidshake_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_avoidshake_0_0 || ORIG_REF_NAME==design_1_avoidshake_0_0}]

# XDC: bd/design_1/design_1_ooc.xdc
