# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
  set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Labtools 27-147} -limit 4294967295
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]

read_ip C:/xup/fpga_flow/labs/lab4_ipi/lab4_ipi.srcs/sources_1/ip/clk_core/clk_core.xci
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property is_locked true [get_files C:/xup/fpga_flow/labs/lab4_ipi/lab4_ipi.srcs/sources_1/ip/clk_core/clk_core.xci]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/xup/fpga_flow/labs/lab4_ipi/lab4_ipi.cache/wt [current_project]
set_property parent.project_dir C:/xup/fpga_flow/labs/lab4_ipi [current_project]
catch { write_hwdef -file clk_core.hwdef }
synth_design -top clk_core -part xc7a35tcpg236-1 -mode out_of_context

rename_ref -prefix_all clk_core_
write_checkpoint -noxdef clk_core.dcp
report_utilization -file clk_core_utilization_synth.rpt -pb clk_core_utilization_synth.pb
if { [catch {
  file copy -force C:/xup/fpga_flow/labs/lab4_ipi/lab4_ipi.runs/clk_core_synth_1/clk_core.dcp C:/xup/fpga_flow/labs/lab4_ipi/lab4_ipi.srcs/sources_1/ip/clk_core/clk_core.dcp
  write_verilog -force -mode synth_stub C:/xup/fpga_flow/labs/lab4_ipi/lab4_ipi.srcs/sources_1/ip/clk_core/clk_core_stub.v
  write_vhdl -force -mode synth_stub C:/xup/fpga_flow/labs/lab4_ipi/lab4_ipi.srcs/sources_1/ip/clk_core/clk_core_stub.vhdl
  write_verilog -force -mode funcsim C:/xup/fpga_flow/labs/lab4_ipi/lab4_ipi.srcs/sources_1/ip/clk_core/clk_core_funcsim.v
  write_vhdl -force -mode funcsim C:/xup/fpga_flow/labs/lab4_ipi/lab4_ipi.srcs/sources_1/ip/clk_core/clk_core_funcsim.vhdl
} _RESULT ] } { 
  send_msg_id runtcl-3 error "Unable to successfully create or copy supporting IP files."
  return -code error
}
