# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/xup/fpga_flow/labs/lab4_ipi/lab4_ipi.srcs/sources_1/ip/clk_core/clk_core.xci
# IP: The module: 'clk_core' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/xup/fpga_flow/labs/lab4_ipi/lab4_ipi.srcs/sources_1/ip/clk_core/clk_core.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_core'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/xup/fpga_flow/labs/lab4_ipi/lab4_ipi.srcs/sources_1/ip/clk_core/clk_core_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_core'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/xup/fpga_flow/labs/lab4_ipi/lab4_ipi.srcs/sources_1/ip/clk_core/clk_core_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_core'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: C:/xup/fpga_flow/labs/lab4_ipi/lab4_ipi.srcs/sources_1/ip/clk_core/clk_core.xci
# IP: The module: 'clk_core' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/xup/fpga_flow/labs/lab4_ipi/lab4_ipi.srcs/sources_1/ip/clk_core/clk_core.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_core'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/xup/fpga_flow/labs/lab4_ipi/lab4_ipi.srcs/sources_1/ip/clk_core/clk_core_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_core'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/xup/fpga_flow/labs/lab4_ipi/lab4_ipi.srcs/sources_1/ip/clk_core/clk_core_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_core'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
