set_property PACKAGE_PIN W5 [get_ports CLK]
set_property IOSTANDARD LVCMOS33 [get_ports CLK]
set_property PACKAGE_PIN V8 [get_ports {a_to_g[3]}]
set_property PACKAGE_PIN U8 [get_ports {a_to_g[4]}]
set_property PACKAGE_PIN W6 [get_ports {a_to_g[5]}]
set_property PACKAGE_PIN W7 [get_ports {a_to_g[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g[6]}]
set_property PACKAGE_PIN W4 [get_ports {pos[3]}]
set_property PACKAGE_PIN V4 [get_ports {pos[2]}]
set_property PACKAGE_PIN U4 [get_ports {pos[1]}]
set_property PACKAGE_PIN U2 [get_ports {pos[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pos[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pos[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pos[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pos[3]}]
set_property PACKAGE_PIN W19 [get_ports Switch]
set_property IOSTANDARD LVCMOS33 [get_ports Switch]
set_property PACKAGE_PIN V16 [get_ports Reset]
set_property IOSTANDARD LVCMOS33 [get_ports rst2]
set_property IOSTANDARD LVCMOS33 [get_ports Reset]
set_property PACKAGE_PIN W16 [get_ports clr]
set_property IOSTANDARD LVCMOS33 [get_ports clr]
set_property PACKAGE_PIN W17 [get_ports {control[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {control[0]}]
set_property PACKAGE_PIN V15 [get_ports {control[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {control[1]}]


set_property PACKAGE_PIN U5 [get_ports {a_to_g[2]}]
set_property PACKAGE_PIN V5 [get_ports {a_to_g[1]}]
set_property PACKAGE_PIN U7 [get_ports {a_to_g[0]}]




set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property PACKAGE_PIN V17 [get_ports rst]
