set_property IOSTANDARD LVCMOS33 [get_ports a]
set_property IOSTANDARD LVCMOS33 [get_ports a_1]
set_property IOSTANDARD LVCMOS33 [get_ports a_2]
set_property IOSTANDARD LVCMOS33 [get_ports a_3]
set_property IOSTANDARD LVCMOS33 [get_ports BCD_A]
set_property IOSTANDARD LVCMOS33 [get_ports BCD_B]
set_property IOSTANDARD LVCMOS33 [get_ports BCD_C]
set_property IOSTANDARD LVCMOS33 [get_ports BCD_D]
set_property IOSTANDARD LVCMOS33 [get_ports LT_n]
set_property IOSTANDARD LVCMOS33 [get_ports RBI_n]
set_property IOSTANDARD LVCMOS33 [get_ports y_1]
set_property IOSTANDARD LVCMOS33 [get_ports y_2]
set_property IOSTANDARD LVCMOS33 [get_ports y_3]
set_property IOSTANDARD LVCMOS33 [get_ports y_4]
set_property PACKAGE_PIN V17 [get_ports BCD_A]
set_property PACKAGE_PIN V16 [get_ports BCD_B]
set_property PACKAGE_PIN W16 [get_ports BCD_C]
set_property PACKAGE_PIN W17 [get_ports BCD_D]
set_property PACKAGE_PIN W15 [get_ports a]
set_property PACKAGE_PIN V15 [get_ports a_1]
set_property PACKAGE_PIN W14 [get_ports a_2]
set_property PACKAGE_PIN R2 [get_ports LT_n]
set_property PACKAGE_PIN T1 [get_ports RBI_n]
set_property PACKAGE_PIN W4 [get_ports y_1]
set_property PACKAGE_PIN V4 [get_ports y_2]
set_property PACKAGE_PIN U4 [get_ports y_3]
set_property PACKAGE_PIN U2 [get_ports y_4]


set_property PACKAGE_PIN W13 [get_ports a_3]


set_property IOSTANDARD LVCMOS33 [get_ports a_4]
set_property IOSTANDARD LVCMOS33 [get_ports b]
set_property IOSTANDARD LVCMOS33 [get_ports c]
set_property IOSTANDARD LVCMOS33 [get_ports BI_RBO_n]
set_property IOSTANDARD LVCMOS33 [get_ports d]
set_property IOSTANDARD LVCMOS33 [get_ports e]
set_property IOSTANDARD LVCMOS33 [get_ports f]
set_property IOSTANDARD LVCMOS33 [get_ports g]
set_property PACKAGE_PIN W7 [get_ports a_4]
set_property PACKAGE_PIN W6 [get_ports b]
set_property PACKAGE_PIN U8 [get_ports c]
set_property PACKAGE_PIN V8 [get_ports d]
set_property PACKAGE_PIN U5 [get_ports e]
set_property PACKAGE_PIN V5 [get_ports f]
set_property PACKAGE_PIN U7 [get_ports g]
set_property PACKAGE_PIN U1 [get_ports BI_RBO_n]
