# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
add_files -quiet C:/Xilinx_Lab/lab_vga/lab_vga.runs/clk_wiz_0_synth_1/clk_wiz_0.dcp
set_property used_in_implementation false [get_files C:/Xilinx_Lab/lab_vga/lab_vga.runs/clk_wiz_0_synth_1/clk_wiz_0.dcp]
read_verilog -library xil_defaultlib C:/Xilinx_Lab/lab_vga/lab_vga.srcs/sources_1/imports/file_vga/vga.v
read_xdc C:/Xilinx_Lab/lab_vga/lab_vga.srcs/constrs_1/imports/file_vga/vga.xdc
set_property used_in_implementation false [get_files C:/Xilinx_Lab/lab_vga/lab_vga.srcs/constrs_1/imports/file_vga/vga.xdc]

read_xdc dont_buffer.xdc
set_property used_in_implementation false [get_files dont_buffer.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Xilinx_Lab/lab_vga/lab_vga.cache/wt [current_project]
set_property parent.project_dir C:/Xilinx_Lab/lab_vga [current_project]
catch { write_hwdef -file vga.hwdef }
synth_design -top vga -part xc7a35tcpg236-1
write_checkpoint vga.dcp
report_utilization -file vga_utilization_synth.rpt -pb vga_utilization_synth.pb
