#Nexys4
set_property PACKAGE_PIN U9 [get_ports SW0]
set_property IOSTANDARD LVCMOS33 [get_ports SW0]
set_property PACKAGE_PIN U8 [get_ports SW1]
set_property IOSTANDARD LVCMOS33 [get_ports SW1]
set_property PACKAGE_PIN R7 [get_ports SW2]
set_property IOSTANDARD LVCMOS33 [get_ports SW2]
set_property PACKAGE_PIN R6 [get_ports SW3]
set_property IOSTANDARD LVCMOS33 [get_ports SW3]
set_property PACKAGE_PIN R5 [get_ports SW4]
set_property IOSTANDARD LVCMOS33 [get_ports SW4]
set_property PACKAGE_PIN V7 [get_ports SW5]
set_property IOSTANDARD LVCMOS33 [get_ports SW5]
set_property PACKAGE_PIN V6 [get_ports SW6]
set_property IOSTANDARD LVCMOS33 [get_ports SW6]

set_property PACKAGE_PIN T8 [get_ports LD0]
set_property IOSTANDARD LVCMOS33 [get_ports LD0]
set_property PACKAGE_PIN V9 [get_ports LD1]
set_property IOSTANDARD LVCMOS33 [get_ports LD1]
set_property PACKAGE_PIN R8 [get_ports LD2]
set_property IOSTANDARD LVCMOS33 [get_ports LD2]
set_property PACKAGE_PIN T6 [get_ports LD3]
set_property IOSTANDARD LVCMOS33 [get_ports LD3]
set_property PACKAGE_PIN T5 [get_ports LD4]
set_property IOSTANDARD LVCMOS33 [get_ports LD4]
set_property PACKAGE_PIN T4 [get_ports LD5]
set_property IOSTANDARD LVCMOS33 [get_ports LD5]
set_property PACKAGE_PIN U7 [get_ports LD6]
set_property IOSTANDARD LVCMOS33 [get_ports LD6]


