# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1}]

# IP: bd/design_1/ip/design_1_D_FlipFlop_Set_Reset_0_0/design_1_D_FlipFlop_Set_Reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_D_FlipFlop_Set_Reset_0_0 || ORIG_REF_NAME==design_1_D_FlipFlop_Set_Reset_0_0}]

# IP: bd/design_1/ip/design_1_D_FlipFlop_Set_Reset_0_1/design_1_D_FlipFlop_Set_Reset_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_D_FlipFlop_Set_Reset_0_1 || ORIG_REF_NAME==design_1_D_FlipFlop_Set_Reset_0_1}]

# IP: bd/design_1/ip/design_1_xup_nand2_0_0/design_1_xup_nand2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_nand2_0_0 || ORIG_REF_NAME==design_1_xup_nand2_0_0}]

# IP: bd/design_1/ip/design_1_xup_nand2_0_1/design_1_xup_nand2_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_nand2_0_1 || ORIG_REF_NAME==design_1_xup_nand2_0_1}]

# IP: bd/design_1/ip/design_1_xup_nand2_0_2/design_1_xup_nand2_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_nand2_0_2 || ORIG_REF_NAME==design_1_xup_nand2_0_2}]

# IP: bd/design_1/ip/design_1_xup_inv_0_0/design_1_xup_inv_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_inv_0_0 || ORIG_REF_NAME==design_1_xup_inv_0_0}]

# IP: bd/design_1/ip/design_1_xup_nand2_0_3/design_1_xup_nand2_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_nand2_0_3 || ORIG_REF_NAME==design_1_xup_nand2_0_3}]

# IP: bd/design_1/ip/design_1_xup_nand2_0_4/design_1_xup_nand2_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_nand2_0_4 || ORIG_REF_NAME==design_1_xup_nand2_0_4}]

# IP: bd/design_1/ip/design_1_xup_nand2_0_5/design_1_xup_nand2_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_nand2_0_5 || ORIG_REF_NAME==design_1_xup_nand2_0_5}]

# IP: bd/design_1/ip/design_1_xup_inv_0_1/design_1_xup_inv_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_inv_0_1 || ORIG_REF_NAME==design_1_xup_inv_0_1}]

# IP: bd/design_1/ip/design_1_xup_xor2_0_0/design_1_xup_xor2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_xor2_0_0 || ORIG_REF_NAME==design_1_xup_xor2_0_0}]

# IP: bd/design_1/ip/design_1_xup_nand2_3_0/design_1_xup_nand2_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_nand2_3_0 || ORIG_REF_NAME==design_1_xup_nand2_3_0}]

# IP: bd/design_1/ip/design_1_xup_nand2_3_1/design_1_xup_nand2_3_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_nand2_3_1 || ORIG_REF_NAME==design_1_xup_nand2_3_1}]

# IP: bd/design_1/ip/design_1_xup_nand2_3_2/design_1_xup_nand2_3_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_nand2_3_2 || ORIG_REF_NAME==design_1_xup_nand2_3_2}]

# IP: bd/design_1/ip/design_1_xup_inv_1_0/design_1_xup_inv_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_inv_1_0 || ORIG_REF_NAME==design_1_xup_inv_1_0}]

# IP: bd/design_1/ip/design_1_xup_nand3_0_0/design_1_xup_nand3_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_nand3_0_0 || ORIG_REF_NAME==design_1_xup_nand3_0_0}]

# IP: bd/design_1/ip/design_1_xup_nand3_0_1/design_1_xup_nand3_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_nand3_0_1 || ORIG_REF_NAME==design_1_xup_nand3_0_1}]

# IP: bd/design_1/ip/design_1_xup_nand3_0_2/design_1_xup_nand3_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_nand3_0_2 || ORIG_REF_NAME==design_1_xup_nand3_0_2}]

# IP: bd/design_1/ip/design_1_xup_nand3_0_3/design_1_xup_nand3_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_nand3_0_3 || ORIG_REF_NAME==design_1_xup_nand3_0_3}]

# IP: bd/design_1/ip/design_1_xup_inv_2_0/design_1_xup_inv_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_inv_2_0 || ORIG_REF_NAME==design_1_xup_inv_2_0}]

# IP: bd/design_1/ip/design_1_xup_xor2_0_1/design_1_xup_xor2_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_xor2_0_1 || ORIG_REF_NAME==design_1_xup_xor2_0_1}]

# IP: bd/design_1/ip/design_1_xup_nand3_0_4/design_1_xup_nand3_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_nand3_0_4 || ORIG_REF_NAME==design_1_xup_nand3_0_4}]

# IP: bd/design_1/ip/design_1_xup_nand4_0_0/design_1_xup_nand4_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_nand4_0_0 || ORIG_REF_NAME==design_1_xup_nand4_0_0}]

# IP: bd/design_1/ip/design_1_xup_nand4_0_1/design_1_xup_nand4_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_nand4_0_1 || ORIG_REF_NAME==design_1_xup_nand4_0_1}]

# IP: bd/design_1/ip/design_1_xup_xor2_0_2/design_1_xup_xor2_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_xor2_0_2 || ORIG_REF_NAME==design_1_xup_xor2_0_2}]

# IP: bd/design_1/ip/design_1_xup_xor2_0_3/design_1_xup_xor2_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_xor2_0_3 || ORIG_REF_NAME==design_1_xup_xor2_0_3}]

# IP: bd/design_1/ip/design_1_xup_xor2_0_4/design_1_xup_xor2_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_xor2_0_4 || ORIG_REF_NAME==design_1_xup_xor2_0_4}]

# IP: bd/design_1/ip/design_1_xup_xor2_0_5/design_1_xup_xor2_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_xor2_0_5 || ORIG_REF_NAME==design_1_xup_xor2_0_5}]

# IP: bd/design_1/ip/design_1_xup_inv_2_1/design_1_xup_inv_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_inv_2_1 || ORIG_REF_NAME==design_1_xup_inv_2_1}]

# IP: bd/design_1/ip/design_1_xup_nand3_3_0/design_1_xup_nand3_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_nand3_3_0 || ORIG_REF_NAME==design_1_xup_nand3_3_0}]

# IP: bd/design_1/ip/design_1_xup_xor2_2_0/design_1_xup_xor2_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_xor2_2_0 || ORIG_REF_NAME==design_1_xup_xor2_2_0}]

# IP: bd/design_1/ip/design_1_xup_nand4_1_0/design_1_xup_nand4_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_nand4_1_0 || ORIG_REF_NAME==design_1_xup_nand4_1_0}]

# XDC: bd/design_1/design_1_ooc.xdc
