# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
  set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Labtools 27-147} -limit 4294967295
create_project -in_memory -part xc7a35tcpg236-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
set_property ip_repo_paths C:/Users/hongyuc/Desktop/digital_base_IP [current_fileset]
add_files -quiet C:/xilinx_workspace/bluetooth_uart/bluetooth_uart.runs/UART_0_synth_1/UART_0.dcp
set_property used_in_implementation false [get_files C:/xilinx_workspace/bluetooth_uart/bluetooth_uart.runs/UART_0_synth_1/UART_0.dcp]
read_verilog -library xil_defaultlib {
  C:/xilinx_workspace/bluetooth_uart/bluetooth_uart.srcs/sources_1/imports/sources_1/imports/new/seg7.v
  C:/xilinx_workspace/bluetooth_uart/bluetooth_uart.srcs/sources_1/imports/sources_1/imports/new/display.v
  C:/xilinx_workspace/bluetooth_uart/bluetooth_uart.srcs/sources_1/imports/sources_1/imports/new/binbcd8.v
  C:/xilinx_workspace/bluetooth_uart/bluetooth_uart.srcs/sources_1/imports/sources_1/new/bluetooth_top.v
}
read_xdc C:/xilinx_workspace/bluetooth_uart/bluetooth_uart.srcs/constrs_1/new/bluetooth_uart.xdc
set_property used_in_implementation false [get_files C:/xilinx_workspace/bluetooth_uart/bluetooth_uart.srcs/constrs_1/new/bluetooth_uart.xdc]

read_xdc dont_buffer.xdc
set_property used_in_implementation false [get_files dont_buffer.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/xilinx_workspace/bluetooth_uart/bluetooth_uart.cache/wt [current_project]
set_property parent.project_dir C:/xilinx_workspace/bluetooth_uart [current_project]
catch { write_hwdef -file bluetooth_top.hwdef }
synth_design -top bluetooth_top -part xc7a35tcpg236-1
write_checkpoint bluetooth_top.dcp
report_utilization -file bluetooth_top_utilization_synth.rpt -pb bluetooth_top_utilization_synth.pb
