# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/sss.xdc

# Block Designs: bd/sss/sss.bd
# Block Designs: The module: 'sss' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: bd/sss/ip/sss_BCD2SEG7_0_0/sss_BCD2SEG7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sss_BCD2SEG7_0_0 || ORIG_REF_NAME==sss_BCD2SEG7_0_0}]

# IP: bd/sss/ip/sss_xup_inv_0_1/sss_xup_inv_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sss_xup_inv_0_1 || ORIG_REF_NAME==sss_xup_inv_0_1}]

# IP: bd/sss/ip/sss_xup_inv_0_2/sss_xup_inv_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sss_xup_inv_0_2 || ORIG_REF_NAME==sss_xup_inv_0_2}]

# IP: bd/sss/ip/sss_xup_inv_0_3/sss_xup_inv_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sss_xup_inv_0_3 || ORIG_REF_NAME==sss_xup_inv_0_3}]

# IP: bd/sss/ip/sss_xup_inv_0_4/sss_xup_inv_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sss_xup_inv_0_4 || ORIG_REF_NAME==sss_xup_inv_0_4}]

# XDC: bd/sss/sss_ooc.xdc
