# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
set_property ip_repo_paths C:/Users/hongyuc/Desktop/digital_base_IP [current_fileset]

read_ip C:/xilinx_workspace/bluetooth_uart/bluetooth_uart.srcs/sources_1/ip/UART_0/UART_0.xci
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property is_locked true [get_files C:/xilinx_workspace/bluetooth_uart/bluetooth_uart.srcs/sources_1/ip/UART_0/UART_0.xci]

set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/xilinx_workspace/bluetooth_uart/bluetooth_uart.cache/wt [current_project]
set_property parent.project_dir C:/xilinx_workspace/bluetooth_uart [current_project]
catch { write_hwdef -file UART_0.hwdef }
synth_design -top UART_0 -part xc7a35tcpg236-1 -mode out_of_context

rename_ref -prefix_all UART_0_
write_checkpoint -noxdef UART_0.dcp
report_utilization -file UART_0_utilization_synth.rpt -pb UART_0_utilization_synth.pb
if { [catch {
  file copy -force C:/xilinx_workspace/bluetooth_uart/bluetooth_uart.runs/UART_0_synth_1/UART_0.dcp C:/xilinx_workspace/bluetooth_uart/bluetooth_uart.srcs/sources_1/ip/UART_0/UART_0.dcp
  write_verilog -force -mode synth_stub C:/xilinx_workspace/bluetooth_uart/bluetooth_uart.srcs/sources_1/ip/UART_0/UART_0_stub.v
  write_vhdl -force -mode synth_stub C:/xilinx_workspace/bluetooth_uart/bluetooth_uart.srcs/sources_1/ip/UART_0/UART_0_stub.vhdl
  write_verilog -force -mode funcsim C:/xilinx_workspace/bluetooth_uart/bluetooth_uart.srcs/sources_1/ip/UART_0/UART_0_funcsim.v
  write_vhdl -force -mode funcsim C:/xilinx_workspace/bluetooth_uart/bluetooth_uart.srcs/sources_1/ip/UART_0/UART_0_funcsim.vhdl
} _RESULT ] } { 
  send_msg_id runtcl-3 error "Unable to successfully create or copy supporting IP files."
  return -code error
}
