# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Users/73974/Documents/vivado/实验九（5）/实验九（5）.runs/synth_1/.Xil/Vivado-12416-surface/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7a35tcpg236-1
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog {
      C:/Users/73974/Documents/vivado/实验九（5）/实验九（5）.srcs/sources_1/bd/sy9/hdl/sy9.v
      c:/Users/73974/Documents/vivado/实验九（5）/实验九（5）.srcs/sources_1/bd/sy9/ipshared/0b64/D_FlipFlop_Set_Reset.v
      c:/Users/73974/Documents/vivado/实验九（5）/实验九（5）.srcs/sources_1/bd/sy9/ip/sy9_D_FlipFlop_Set_Reset_0_0/synth/sy9_D_FlipFlop_Set_Reset_0_0.v
      c:/Users/73974/Documents/vivado/实验九（5）/实验九（5）.srcs/sources_1/bd/sy9/ipshared/35a3/xup_nand2.srcs/sources_1/new/xup_nand2.v
      c:/Users/73974/Documents/vivado/实验九（5）/实验九（5）.srcs/sources_1/bd/sy9/ip/sy9_xup_nand2_0_0/synth/sy9_xup_nand2_0_0.v
      c:/Users/73974/Documents/vivado/实验九（5）/实验九（5）.srcs/sources_1/bd/sy9/ip/sy9_xup_nand2_0_3/synth/sy9_xup_nand2_0_3.v
      c:/Users/73974/Documents/vivado/实验九（5）/实验九（5）.srcs/sources_1/bd/sy9/ip/sy9_xup_nand2_0_4/synth/sy9_xup_nand2_0_4.v
      c:/Users/73974/Documents/vivado/实验九（5）/实验九（5）.srcs/sources_1/bd/sy9/ipshared/e3e7/xup_inv.srcs/sources_1/new/xup_inv.v
      c:/Users/73974/Documents/vivado/实验九（5）/实验九（5）.srcs/sources_1/bd/sy9/ip/sy9_xup_inv_0_1/synth/sy9_xup_inv_0_1.v
      c:/Users/73974/Documents/vivado/实验九（5）/实验九（5）.srcs/sources_1/bd/sy9/ip/sy9_xup_nand2_1_0/synth/sy9_xup_nand2_1_0.v
      c:/Users/73974/Documents/vivado/实验九（5）/实验九（5）.srcs/sources_1/bd/sy9/ip/sy9_xup_nand2_1_1/synth/sy9_xup_nand2_1_1.v
      c:/Users/73974/Documents/vivado/实验九（5）/实验九（5）.srcs/sources_1/bd/sy9/ip/sy9_xup_nand2_1_2/synth/sy9_xup_nand2_1_2.v
      c:/Users/73974/Documents/vivado/实验九（5）/实验九（5）.srcs/sources_1/bd/sy9/ip/sy9_xup_inv_0_2/synth/sy9_xup_inv_0_2.v
      c:/Users/73974/Documents/vivado/实验九（5）/实验九（5）.srcs/sources_1/bd/sy9/ipshared/7bd1/xup_xor2.srcs/sources_1/new/xup_xor2.v
      c:/Users/73974/Documents/vivado/实验九（5）/实验九（5）.srcs/sources_1/bd/sy9/ip/sy9_xup_xor2_0_0/synth/sy9_xup_xor2_0_0.v
      c:/Users/73974/Documents/vivado/实验九（5）/实验九（5）.srcs/sources_1/bd/sy9/ipshared/f5b3/xup_nand3.srcs/sources_1/new/xup_nand3.v
      c:/Users/73974/Documents/vivado/实验九（5）/实验九（5）.srcs/sources_1/bd/sy9/ip/sy9_xup_nand3_0_4/synth/sy9_xup_nand3_0_4.v
      c:/Users/73974/Documents/vivado/实验九（5）/实验九（5）.srcs/sources_1/bd/sy9/ip/sy9_D_FlipFlop_Set_Reset_0_2/synth/sy9_D_FlipFlop_Set_Reset_0_2.v
      c:/Users/73974/Documents/vivado/实验九（5）/实验九（5）.srcs/sources_1/bd/sy9/ip/sy9_xup_nand2_1_3/synth/sy9_xup_nand2_1_3.v
      c:/Users/73974/Documents/vivado/实验九（5）/实验九（5）.srcs/sources_1/bd/sy9/ip/sy9_xup_nand2_1_4/synth/sy9_xup_nand2_1_4.v
      c:/Users/73974/Documents/vivado/实验九（5）/实验九（5）.srcs/sources_1/bd/sy9/ip/sy9_xup_nand2_1_5/synth/sy9_xup_nand2_1_5.v
      c:/Users/73974/Documents/vivado/实验九（5）/实验九（5）.srcs/sources_1/bd/sy9/ip/sy9_xup_inv_1_0/synth/sy9_xup_inv_1_0.v
      c:/Users/73974/Documents/vivado/实验九（5）/实验九（5）.srcs/sources_1/bd/sy9/ip/sy9_xup_nand3_0_5/synth/sy9_xup_nand3_0_5.v
      c:/Users/73974/Documents/vivado/实验九（5）/实验九（5）.srcs/sources_1/bd/sy9/ip/sy9_xup_nand3_0_6/synth/sy9_xup_nand3_0_6.v
      c:/Users/73974/Documents/vivado/实验九（5）/实验九（5）.srcs/sources_1/bd/sy9/ip/sy9_xup_nand3_0_7/synth/sy9_xup_nand3_0_7.v
      c:/Users/73974/Documents/vivado/实验九（5）/实验九（5）.srcs/sources_1/bd/sy9/ip/sy9_xup_inv_2_0/synth/sy9_xup_inv_2_0.v
      c:/Users/73974/Documents/vivado/实验九（5）/实验九（5）.srcs/sources_1/bd/sy9/ip/sy9_xup_nand3_0_8/synth/sy9_xup_nand3_0_8.v
      c:/Users/73974/Documents/vivado/实验九（5）/实验九（5）.srcs/sources_1/bd/sy9/ip/sy9_xup_nand2_8_0/synth/sy9_xup_nand2_8_0.v
      c:/Users/73974/Documents/vivado/实验九（5）/实验九（5）.srcs/sources_1/bd/sy9/ip/sy9_xup_nand2_7_0/synth/sy9_xup_nand2_7_0.v
      c:/Users/73974/Documents/vivado/实验九（5）/实验九（5）.srcs/sources_1/bd/sy9/ip/sy9_xup_nand2_7_1/synth/sy9_xup_nand2_7_1.v
      c:/Users/73974/Documents/vivado/实验九（5）/实验九（5）.srcs/sources_1/bd/sy9/ip/sy9_xup_nand2_7_2/synth/sy9_xup_nand2_7_2.v
      c:/Users/73974/Documents/vivado/实验九（5）/实验九（5）.srcs/sources_1/bd/sy9/ip/sy9_xup_inv_2_1/synth/sy9_xup_inv_2_1.v
      c:/Users/73974/Documents/vivado/实验九（5）/实验九（5）.srcs/sources_1/bd/sy9/ipshared/35c5/xup_nand4.srcs/sources_1/new/xup_nand4.v
      c:/Users/73974/Documents/vivado/实验九（5）/实验九（5）.srcs/sources_1/bd/sy9/ip/sy9_xup_nand4_0_10/synth/sy9_xup_nand4_0_10.v
      c:/Users/73974/Documents/vivado/实验九（5）/实验九（5）.srcs/sources_1/bd/sy9/ip/sy9_xup_nand4_0_11/synth/sy9_xup_nand4_0_11.v
      c:/Users/73974/Documents/vivado/实验九（5）/实验九（5）.srcs/sources_1/bd/sy9/ip/sy9_xup_nand2_10_0/synth/sy9_xup_nand2_10_0.v
      c:/Users/73974/Documents/vivado/实验九（5）/实验九（5）.srcs/sources_1/bd/sy9/ip/sy9_xup_nand4_1_0/synth/sy9_xup_nand4_1_0.v
      c:/Users/73974/Documents/vivado/实验九（5）/实验九（5）.srcs/sources_1/bd/sy9/ip/sy9_xup_nand3_3_1/synth/sy9_xup_nand3_3_1.v
      c:/Users/73974/Documents/vivado/实验九（5）/实验九（5）.srcs/sources_1/bd/sy9/ip/sy9_xup_nand2_13_0/synth/sy9_xup_nand2_13_0.v
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top sy9
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "C:/Users/73974/Documents/vivado/实验九（5）/实验九（5）.runs/synth_1/.Xil/Vivado-12416-surface/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }

    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }


    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
