# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/73974/Documents/vivado/clock/clock_v1.1/clock_v1.1.cache/wt [current_project]
set_property parent.project_path C:/Users/73974/Documents/vivado/clock/clock_v1.1/clock_v1.1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/Users/73974/Documents/vivado/clock/clock_v1.1/clock_v1.1.srcs/sources_1/new/clock.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/73974/Documents/vivado/clock/clock_v1.1/clock_v1.1.srcs/constrs_1/new/clock.xdc
set_property used_in_implementation false [get_files C:/Users/73974/Documents/vivado/clock/clock_v1.1/clock_v1.1.srcs/constrs_1/new/clock.xdc]


synth_design -top clock_top -part xc7a35tcpg236-1


write_checkpoint -force -noxdef clock_top.dcp

catch { report_utilization -file clock_top_utilization_synth.rpt -pb clock_top_utilization_synth.pb }
