# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
  set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Labtools 27-147} -limit 4294967295
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
read_verilog -library xil_defaultlib {
  C:/xup/fpga_flow/labs/lab2/lab2.srcs/sources_1/imports/lab2/uart_rx_ctl.v
  C:/xup/fpga_flow/labs/lab2/lab2.srcs/sources_1/imports/lab2/uart_baud_gen.v
  C:/xup/fpga_flow/labs/lab2/lab2.srcs/sources_1/imports/lab2/meta_harden.v
  C:/xup/fpga_flow/labs/lab2/lab2.srcs/sources_1/imports/lab2/uart_rx.v
  C:/xup/fpga_flow/labs/lab2/lab2.srcs/sources_1/imports/lab2/led_ctl.v
  C:/xup/fpga_flow/labs/lab2/lab2.srcs/sources_1/imports/lab2/uart_led.v
}
read_xdc C:/xup/fpga_flow/labs/lab2/lab2.srcs/constrs_1/imports/lab2/uart_led_timing.xdc
set_property used_in_implementation false [get_files C:/xup/fpga_flow/labs/lab2/lab2.srcs/constrs_1/imports/lab2/uart_led_timing.xdc]

read_xdc C:/xup/fpga_flow/labs/lab2/lab2.srcs/constrs_1/imports/lab2/uart_led_pins.xdc
set_property used_in_implementation false [get_files C:/xup/fpga_flow/labs/lab2/lab2.srcs/constrs_1/imports/lab2/uart_led_pins.xdc]

set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/xup/fpga_flow/labs/lab2/lab2.cache/wt [current_project]
set_property parent.project_dir C:/xup/fpga_flow/labs/lab2 [current_project]
catch { write_hwdef -file uart_led.hwdef }
synth_design -top uart_led -part xc7a100tcsg324-1
write_checkpoint uart_led.dcp
report_utilization -file uart_led_utilization_synth.rpt -pb uart_led_utilization_synth.pb
