// RhinoRESStrings.h - Contains #defines for each string value contained in RhinoRES
//

#define RSIDS_FILE_MISSING_FMT          9800
#define RSIDS_WARNING					9801
#define RSIDS_VERSION_FMT               9802
#define RSIDS_REGGIE_FROM_CLIPBOARD     9803
#define RSIDS_STANDARD                  9804
#define RSIDS_TEMPORARY                 9805
#define RSIDS_ENTERPRISE                9806
#define RSIDS_SITE_LICENSE              9807
#define RSIDS_DEPARTMENT                9808
#define RSIDS_SECURE                    9809
#define RSIDS_PROFESSIONAL              9810
#define RSIDS_CORPORATE                 9811
#define RSIDS_BRONZE		            9812
#define RSIDS_SILVER		            9813
#define RSIDS_GOLD						9814
#define RSIDS_UPDATE                    9815
#define RSIDS_UPDATE_PERIOD_FMT         9816
#define RSIDS_TRIAL                     9817
#define RSIDS_TRIAL_DAYS_REMAINING_FMT  9818
#define RSIDS_TRIAL_EXPIRED             9819
#define RSIDS_CUSTOMER_NAME_EMPTY_FMT   9820
#define RSIDS_INVALID_CUSTOMER_ID       9821
#define RSIDS_USERID                    9822
#define RSIDS_COMPUTER                  9823
#define RSIDS_USER_NAME                 9824
#define RSIDS_DIDYOUKNOW                9825
#define RSIDS_TIP_FILE_MISSING          9826
#define RSIDS_WELCOME                   9827
#define RSIDS_LANGUAGE                  9828
#define RSIDS_DISTRIBUTOR_HOME          9829
#define RSIDS_FV_DESC                   9830
// #define RSIDS_FVSDK_DESC                9831			available
#define RSIDS_D4_DESC                   9832
// #define RSIDS_ZP_DESC                   9833			available
#define RSIDS_AS_DESC                   9834
#define RSIDS_SU_DESC                   9835
#define RSIDS_INNOSETUP_CLOSE           9836
#define RSIDS_INNOSETUP_EXIT_CAPTION    9837
#define RSIDS_INNOSETUP_EXIT_TEXT       9838
#define RSIDS_OTHER_PRODUCTS_HEADER     9839
#define RSIDS_OTHER_PRODUCTS_COMMENT    9840
#define RSIDS_NETWORK_INFO              9841
#define RSIDS_NETWORK_INFO_DATA         9842
#define RSIDS_IP4_ADDRESS_FMT           9843
#define RSIDS_SUBNET_MASK_FMT           9844
#define RSIDS_NO_ADAPTERS_FOUND         9845
#define RSIDS_MAC_ADDRESS               9846
#define RSIDS_YES                       9847
#define RSIDS_NO                        9848
#define RSIDS_IP4_DEFAULT_GATEWAY_FMT   9849
#define RSIDS_HOST_NAME                 9850
#define RSIDS_DNS_SUFFIX                9851
#define RSIDS_IP_ROUTING_ENABLED        9852
#define RSIDS_DNS_SERVER_FMT            9853
#define RSIDS_DHCP_ENABLED              9854
#define RSIDS_NETWORK_INFO_CLIPBOARD    9855
#define RSIDS_NEW_VERSION               9856
#define RSIDS_CURRENT_VERSION           9857
#define RSIDS_RELEASE_NOTES             9859
#define RSIDS_FIXES                     9860
#define RSIDS_RETRIEVING_RELEASE_NOTES  9861
#define RSIDS_CONTACTING_UPDATE_SERVER  9862
#define RSIDS_UNLIMITED                 9863
#define RSIDS_IP6_ADDRESS_FMT           9864
#define RSIDS_IP6_DEFAULT_GATEWAY_FMT   9865
#define RSIDS_IP4_DHCP_SERVER_FMT       9866
#define RSIDS_IP6_DHCP_SERVER_FMT       9867
