webtalk_init -webtalk_dir D:\\Xilinx_Proj_Mar\\B3_Lab\\Lab5\\MB_Uart\\Src\\prj\\MB_Uart.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "星期四 三月 5 09:35:49 2015" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2014.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2014.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "59gjjteoao1geljnldcbdbkk1e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2014.4_5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "5" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1425518037947" -context "sdk\\\\hardware/1425518037947"
webtalk_add_data -client sdk -key isZynq -value "false" -context "sdk\\\\hardware/1425518037947"
webtalk_add_data -client sdk -key Processors -value "1" -context "sdk\\\\hardware/1425518037947"
webtalk_add_data -client sdk -key VivadoVersion -value "2014.4" -context "sdk\\\\hardware/1425518037947"
webtalk_add_data -client sdk -key Arch -value "artix7" -context "sdk\\\\hardware/1425518037947"
webtalk_add_data -client sdk -key Device -value "7a35t" -context "sdk\\\\hardware/1425518037947"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1425518037947"
webtalk_add_data -client sdk -key uid -value "1425518258721" -context "sdk\\\\bsp/1425518258721"
webtalk_add_data -client sdk -key hwid -value "1425518037947" -context "sdk\\\\bsp/1425518258721"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1425518258721"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1425518258721"
webtalk_add_data -client sdk -key uid -value "1425518263023" -context "sdk\\\\application/1425518263023"
webtalk_add_data -client sdk -key hwid -value "1425518037947" -context "sdk\\\\application/1425518263023"
webtalk_add_data -client sdk -key bspid -value "1425518258721" -context "sdk\\\\application/1425518263023"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1425518263023"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1425518263023"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1425518263023"
webtalk_transmit -clientid 161298481 -regid "" -xml D:\\Xilinx_Proj_Mar\\B3_Lab\\Lab5\\MB_Uart\\Src\\prj\\MB_Uart.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html D:\\Xilinx_Proj_Mar\\B3_Lab\\Lab5\\MB_Uart\\Src\\prj\\MB_Uart.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm D:\\Xilinx_Proj_Mar\\B3_Lab\\Lab5\\MB_Uart\\Src\\prj\\MB_Uart.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
